# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cTHm28fHayT6tJFbdqlG0q6h6Iu-CXu8
"""

import cv2
import matplotlib.pyplot as plt
from google.colab import files
# Step 1: Upload a face image
print("Upload an image with at least one human face (jpg, png):")
uploaded = files.upload()
image_path = list(uploaded.keys())[0]
# Step 2: Load Haar cascade for face detection

64

face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades +
'haarcascade_frontalface_default.xml')
# Step 3: Read and convert the image to grayscale
img = cv2.imread(image_path)
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
# Step 4: Detect faces
faces = face_cascade.detectMultiScale(gray, scaleFactor=1.1, minNeighbors=5)
# Step 5: Draw rectangles around detected faces
for (x, y, w, h) in faces:
    cv2.rectangle(img, (x, y), (x + w, y + h), (255, 0, 0), 2)
# Step 6: Display the result using matplotlib
img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
plt.figure(figsize=(8, 6))
plt.imshow(img_rgb)
plt.title("Detected Face(s)")
plt.axis('off')
plt.show()

import cv2
import matplotlib.pyplot as plt
from google.colab import files
import os
# Step 1: Upload a short video with a human face
print("Upload a video file (e.g., .mp4, .avi):")
uploaded = files.upload()
video_path = list(uploaded.keys())[0]
# Step 2: Load the Haar Cascade for face detection
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades +
'haarcascade_frontalface_default.xml')
# Step 3: Read video file
cap = cv2.VideoCapture(video_path)
frame_count = 0
while True:
    ret, frame = cap.read()
    if not ret or frame_count >= 100: # limit to 100 frames to avoid long runtime
        break
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(gray, 1.1, 4)
    for (x, y, w, h) in faces:
        cv2.rectangle(frame, (x, y), (x + w, y + h), (0, 255, 0), 2)
    # Convert BGR to RGB for matplotlib
    rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    # Display every 20th frame
    if frame_count % 20 == 0:
        plt.figure(figsize=(8, 5))
        plt.imshow(rgb)
        plt.title(f"Frame {frame_count} with Detected Face(s)")
        plt.axis('off')
        plt.show()

import os

dataset_path = "/content/face_recognition_dataset/Faces"
os.makedirs(dataset_path, exist_ok=True)
print(f"Directory '{dataset_path}' created successfully.")

import os
import cv2
import numpy as np
def load_dataset(dataset_path):
    images = []
    labels = []
    label_dict = {}
    current_label = 0
    if not os.path.exists(dataset_path):
        print(f"Dataset path does not exist: {dataset_path}")
        return [], [], {}
    # Check if dataset_path is a directory or a file
    if os.path.isdir(dataset_path):
        for person_name in os.listdir(dataset_path):
            person_path = os.path.join(dataset_path, person_name)
            if os.path.isdir(person_path):
                label_dict[current_label] = person_name
                for img_name in os.listdir(person_path):
                    img_path = os.path.join(person_path, img_name)
                    img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
                    # Check if image loaded successfully and has valid dimensions
                    if img is not None and img.shape[0] > 0 and img.shape[1] > 0:
                        images.append(img)
                        labels.append(current_label)
                    else:
                        print(f"Failed to load or invalid image: {img_path}") # Print an error message for debugging
                current_label += 1
    else: # Assuming it's a file, but the logic expects a directory structure
        print(f"Expected a directory for dataset, but got a file: {dataset_path}")
        # You might want to add logic here to handle a CSV file with paths if that's the intent

    return images, labels, label_dict

dataset_path = "/content/face_recognition_dataset/Faces" # Corrected path for Colab
# dataset_path = "C:/Users/Najam Ali/Downloads/archive (2)/Dataset" # Original path (commented out)

# Before calling load_dataset, ensure the directory exists or explain how to upload it
if not os.path.exists(dataset_path):
    print(f"Dataset directory not found at {dataset_path}. Please upload your dataset or create the directory structure.")
    # You can add instructions here for uploading a zip file, for example.
    # For now, we'll proceed with empty lists if the dataset isn't there to avoid an error.
    images = []
    labels = []
    label_dict = {}
else:
    images, labels, label_dict = load_dataset(dataset_path)

# Only proceed with recognizer training if there are images
if images:
    # Create and train the LBPH face recognizer
    recognizer = cv2.face.LBPHFaceRecognizer_create()
    recognizer.train(images, np.array(labels))
    # Save the trained model
    recognizer.save('face_recognizer.yml')
    # Save label map to file
    with open("label_map.txt", "w") as f: # Create and open the label map file in write mode ('w')
        for label, name in label_dict.items():
            f.write(f"{label}:{name}\n") # Write each label and name to the file
    print("Model trained and saved.")
else:
    print("No images found to train the recognizer. Skipping model training and saving.")

# --- Code for recognition (assuming model and label_map exist) ---
recognizer = cv2.face.LBPHFaceRecognizer_create()

try:
    recognizer.read("/content/face_recognizer.yml") # Assuming the model will be saved here
except cv2.error as e:
    print(f"Error loading recognizer model: {e}")
    print("Please ensure 'face_recognizer.yml' and 'label_map.txt' exist and are correctly trained.")
    # Exit or handle the error gracefully if the model isn't loaded
    exit()

face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades +
'haarcascade_frontalface_default.xml')

# Load label map
label_map = {}
try:
    with open("label_map.txt", "r") as f:
        for line in f:
            label, name = line.strip().split(":")
            label_map[int(label)] = name
except FileNotFoundError:
    print("Error: 'label_map.txt' not found. Cannot perform recognition.")
    exit()

# Load captured image and process
# Ensure the image path for recognition is correct and accessible in Colab
recognition_image_path = "/content/HD-wallpaper-lionel-messi-world-cup-mvp-argentina.jpg" # Example path from uploaded files
# recognition_image_path = "C:/Users/Najam Ali/Pictures/sanjay-dutt-wore-a-25-kilo-armour-to-shoot-for-kgf-chapter-2-here-are-the-details-001.jpg" # Original path (commented out)

img = cv2.imread(recognition_image_path)

if img is None:
    print(f"Error: Could not load image from {recognition_image_path} for recognition.")
    print("Please ensure the image exists and the path is correct.")
else:
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(gray, 1.3, 5)

    for (x, y, w, h) in faces:
        roi_gray = gray[y:y+h, x:x+w]
        # Handle case where roi_gray might be empty or invalid
        if roi_gray.shape[0] == 0 or roi_gray.shape[1] == 0:
            print(f"Warning: Skipping empty region of interest at ({x},{y},{w},{h})")
            continue

        label, confidence = recognizer.predict(roi_gray)
        name = label_map.get(label, "Unknown")
        cv2.rectangle(img, (x, y), (x+w, y+h), (0, 255, 0), 2)
        cv2.putText(img, f"{name} ({int(confidence)})", (x, y-10),
        cv2.FONT_HERSHEY_SIMPLEX, 0.8, (0, 255, 0), 2)

    # Show the result
    from matplotlib import pyplot as plt
    plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
    plt.axis('off')
    plt.show()